#server:
#  port: 7000
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.163.10:8848 # 将gateway注册到nacos
#    gateway:
#      discovery:
#        locator:
#          enabled: true # 让gateway从nacos中获取服务信息
#      routes:
#        - id: product_route
#          uri: lb://service-product
#          order: 1
#          predicates:
#            - Path=/api/product-serv/**
#          filters:
#            - StripPrefix=2
#        - id: order_route
#          uri: lb://service-order
#          order: 1
#          predicates:
#            - Path=/api/order-serv/**
#          filters:
#            - StripPrefix=2